from django.db import models

class BlackCards(models.Model):
    id = models.AutoField(max_length="4", primary_key=True)
    text = models.TextField(max_length="200", default='')
    Serious = models.BooleanField(default=False)
    Sex = models.BooleanField(default=False)
    Disaster = models.BooleanField(default=False)
    Disgust = models.BooleanField(default=False)
    Absurd = models.BooleanField(default=False)
    Religion = models.BooleanField(default=False)
    Violence = models.BooleanField(default=False)
    Science = models.BooleanField(default=False)
    Race = models.BooleanField(default=False)
    Politics = models.BooleanField(default=False)
    Heroism = models.BooleanField(default=False)
    Culture = models.BooleanField(default=False)
    Sports = models.BooleanField(default=False)
    Food = models.BooleanField(default=False)
    Arts = models.BooleanField(default=False)
    Male = models.BooleanField(default=False)
    Female = models.BooleanField(default=False)
    Unrealistic = models.BooleanField(default=False)
    Health = models.BooleanField(default=False)
    Poverty = models.BooleanField(default=False)
    Selfish = models.BooleanField(default=False)
    Appeal = models.BooleanField(default=False)
    Others = models.BooleanField(default=False)
    Personality = models.BooleanField(default=False)
    Age = models.BooleanField(default=False)
    Animal = models.BooleanField(default=False)

class WhiteCards(models.Model):
    id = models.AutoField(max_length="4", primary_key=True)
    text = models.TextField(max_length="200", default='')
    Serious = models.BooleanField(default=False)
    Sex = models.BooleanField(default=False)
    Disaster = models.BooleanField(default=False)
    Disgust = models.BooleanField(default=False)
    Absurd = models.BooleanField(default=False)
    Religion = models.BooleanField(default=False)
    Violence = models.BooleanField(default=False)
    Science = models.BooleanField(default=False)
    Race = models.BooleanField(default=False)
    Politics = models.BooleanField(default=False)
    Heroism = models.BooleanField(default=False)
    Culture = models.BooleanField(default=False)
    Sports = models.BooleanField(default=False)
    Food = models.BooleanField(default=False)
    Arts = models.BooleanField(default=False)
    Male = models.BooleanField(default=False)
    Female = models.BooleanField(default=False)
    Unrealistic = models.BooleanField(default=False)
    Health = models.BooleanField(default=False)
    Poverty = models.BooleanField(default=False)
    Selfish = models.BooleanField(default=False)
    Appeal = models.BooleanField(default=False)
    Others = models.BooleanField(default=False)
    Personality = models.BooleanField(default=False)
    Age = models.BooleanField(default=False)
    Animal = models.BooleanField(default=False)

class Hands(models.Model):
    id = models.AutoField(max_length="10", primary_key=True)
    bid = models.IntegerField(default=0)
    numPlayed = models.IntegerField(default=0)

class HandWhites(models.Model):
    handID = models.IntegerField(default=0)
    wID = models.IntegerField(default=0)

class Played(models.Model):
    id = models.AutoField(max_length="10", primary_key=True)
    playerID = models.IntegerField(default=0)
    handID = models.IntegerField(default=0)
    wID = models.IntegerField(default=0)

class AIPlayed(models.Model):
    id = models.AutoField(max_length="10", primary_key=True)
    AIver = models.IntegerField(default=0)
    handID = models.IntegerField(default=0)
    wID = models.IntegerField(default=0)

class Judged(models.Model):
    id = models.AutoField(max_length="10", primary_key=True)
    judgeID = models.IntegerField(default=0)
    handID = models.IntegerField(default=0)
    wID = models.IntegerField(default=0)
    AIver = models.IntegerField(default=0)
    AIwin = models.BooleanField(default=False)